#pragma once
#ifndef Tr2InteriorVisualization_H
#define Tr2InteriorVisualization_H

enum VisualizeMethod
{
	VM_NONE,

	VM_WHITE,

	VM_OBJECT_NORMAL,

	VM_TANGENT,
	VM_BITANGENT,

	VM_TEXCOORD0,
	VM_TEXCOORD1,

	VM_TEXELDENSITY0,

	VM_NORMALMAP,

	VM_DIFFUSEMAP,
	VM_SPECULARMAP,
	VM_OVERDRAW,

	VM_EN_ONLY,
	VM_EN_TARGET_DETAIL,
	VM_EN_OUTPUT_DENSITY,
	VM_EN_ALBEDO,
	VM_EN_EMISSIVE,
	VM_EN_OBJECT_TEXCOORD,
	VM_EN_NAUGHTY_PIXELS,
	VM_EN_CHARTS,
	VM_EN_TARGET_CHARTS,

	VM_DEPTH,

	VM_ALL_LIGHTING,
	VM_LIGHT_PRE_PASS_NORMALS,
	VM_LIGHT_PRE_PASS_DEPTH,
	VM_LIGHT_PRE_PASS_WORLD_POSITION,
	VM_LIGHT_PRE_PASS_LIGHTING,
	VM_LIGHT_PRE_PASS_LIGHT_OVERDRAW,
	VM_LIGHT_PRE_PASS_DIFFUSE_LIGHTING,
	VM_LIGHT_PRE_PASS_SPECULAR_LIGHTING,

	VM_OCCLUSION,

	VM_COUNT
};

#endif